rust-lang/rust-playpen

bot.py

It's rather annoying that e.g. expressions returning `()` don't work, this should fix that.

Use `Show` for bot output.

---

bot.py

The regex crate has been moved out of rust to crate.io. So rusti can't
use it as is any more. Removes the reference.

Remove regex reference from rusti

---

static/web.js

https://developer.mozilla.org/docs/Security/MixedContent
Firefox now blocks XHR requests to HTTP sites from HTTPS origins. We do this with the is.gd API call, though their API works on HTTPS too ([demo](https://is.gd/create.php?format=json&url=http%3A%2F%2Fplay.rust-lang.org%3Fcode%3Dfn%2520main%28%29%2520%257B%250A%2520%2520%2520%2520let%2520x%2520%253D%2520StatusCode%28200%29%253B%250A%2520%2520%2520%2520assert!%28x%2520%253D%253D%2520StatusCode%253A%253AOk%29%250A%257D%250A%250A%2523%255Bderive%28PartialEq%29%255D%250Astruct%2520StatusCode%28pub%2520u16%29%253B%250A%250A%2523%255Ballow%28non_snake_case%29%255D%250A%2523%255Ballow%28non_upper_case_globals%29%255D%250Amod%2520StatusCode%2520%257B%250A%2520%2520use%2520super%253A%253AStatusCode%253B%250A%2520%2520pub%2520static%2520Ok%253A …

Move to HTTPS to stop mixed content error

---

static/web.html
static/web.js

This uses Ace's `ext-themelist.js` and `localStorage` to set and remember the user's favorite highlighting theme. It adds one `<select>` tag on the end of the others. All themes are listed alphabetically by their proper name. The default theme is still `GitHub`. 
I've tested this locally using Chrome and `web.py`. Since it only touches the frontend it shouldn't interfere with any of the actual code evaluation.
This is what it looks like:

Added theme support to the frontend using Ace themes.

---

static/web.js

There was an unnecessary loop in the `onchange` event, and the `build_themes` function didn't exactly match the project style (it used single quotes). There was also no reason for `themelist` to be global. This patch doesn't change the end result, but provides greater clarity and speed (when selecting a new theme after load) and removes the unneeded global.
You were so great to accept my patch the first time, but when I noticed these things later it bothered me. I don't want to be a pest, so I'll just offer up this little fix and let you get back to work.

Themelist fixes/enhancements (better style/speed/clarity).

---

static/web.js

allow webkit browser with disabled localStorage (localStorage is `null`)
or private-browsing enable (throw `QUOTA_EXCEEDED_ERR`) to use
rust-playpen.

catch possible errors from localStorage

---

static/web.html

Ace released a new version that fixes several rust highlight problems ( Issue #77 is one of them). This PR simply switches to the new version. Tested locally with web.py.

Ace update v.1.1.9, Fixes #77

---

static/web.html

Maybe it should have its own, but I just linked in the one on rust-lang.org

Use the rust-lang.org favicon

---

static/web.html

The formatting is just `rustc --pretty`, which is known to be subpar and
unidiomatic. This could be reintroduced with rustfmt.

Remove the format button for now.

---

static/web.css

The box-shadow breaks rendering of the dropdown in firefox, and is barely visible in chrome anyway.

Fix graphical glitch on dropdown in firefox

---

static/web.js

The onchange event is not triggered in firefox when a combobox selection is changed via the keyboard. It should listen for onkeyup as well.

Fix onchange keyboard event in firefox

---

static/web.css
static/web.html
static/web.js

This PR adds support for sharing the session via an anonymous Gist.  It changes the 'Share' button to 'Shorten' and adds a 'Gist' button next to it. A new query parameter 'gist' specifies the Gist ID to load.
A Gist-Playground URL looks like this:
[https://play.rust-lang.org/?gist=b5552ad8232f90e3380b&version=stable](https://play.rust-lang.org/?gist=b5552ad8232f90e3380b&version=stable)
Gists with multiple files aren't supported; this will just load the first file it encounters.
This also adds a new function 'httpRequest'.  Unfortunately I didn't notice the existing 'send' function, however that was too restrictive to begin with.  I'll make a separate PR that merges these functions in some way so we don't have any silly repeated code for requesting things.
It's "Part 1" because I would …

Gist integration, part 1

---

bin/evaluate.sh
static/web.html
static/web.js
web.py

See #107 and #32 for some other discussion of this concept.
This approach doesn’t deal with every situation, as it detects a program as either for execution or for testing, but it deals with the most common situation more elegantly than any other approach.
As usual, this code is running at http://temp.chrismorgan.info/rust-playpen/static/web.html, but the actual test functionality won’t work because it’s using play.rust-lang.org for execution and so it doesn’t have the necessary server changes to support it.

Detect tests and treat them as tests, not main.

---

bin/evaluate.sh
static/web.html
static/web.js
web.py

This reverts commits b43d1646cb7548b21631b064269a851fe368e739 and
6f3858caf0ba8602af068a82e5d12e06bd917f18, returning to the state of
c7a1ef4566f72b0628eefccbe09c0251a629fc03.
I’ve tried it out locally and it all works; I’m not sure what precisely
went wrong in the deployment process (after @brson had deployed it, test
mode simply didn’t activate), but I’m now moderately confident it wasn’t
a problem in these changes. Now that @acrichto is back, can we try it
again now?

Revert the reversion of #111 and #114.

---

bin/compile.sh
bin/evaluate.sh
static/web.css
static/web.html
static/web.js
web.py

The compiler can write ANSI colour codes for nicer error messages, so why not use it? I improved a few other cases (like internal server errors which I unsurprisingly triggered while developing—reporting such as connection failures was wrong) while I was at it.
The colour part of it is mildly fragile, as what codes actually get written depends on the terminfo. Most notably, the `^[(B` that seems to come after `^[[m` (turn off all attributes) has baffled me as I haven’t found documentation of what it is, nor do I find it in my termcap for sgr0. Ah well. It doesn’t seem to matter. Hopefully the deployment server will produce the same ANSI codes. If it doesn’t, the ansi2html function may need to be adjusted.
Error codes are hyperlinks to their entries in the error index, which is generated …

Improve compiler output with things like colours.

---

bin/compile.sh
bin/evaluate.sh
static/web.html
static/web.js

This should make colour codes actually work on the server (where `TERM` is presumably unset, based on the experience of landing #121) and ensures stability for the colour codes emitted, constraining it to the basic 16 colour palette which is easier to deal with and more familiar to people (`^[[31m` for red, &c.).
That unknown `^[(B` still appears, though now it’s *before* the `^[[m`, unlike after as it was with my own `TERM=rxvt-unicode-256color`. *Shrug.*

Set TERM=xterm to get colours working well.

---

static/web.html
static/web.js
web.py

Confirmed that `-C llvm-args=-x86-asm-syntax=intel` is harmless when emitting IR.

Add support for intel syntax when emitting asm

---

static/web.js

selectedOptions is not supported in Internet Explorer
I've tested this change locally in FF, Chrome, and IE.

Fix for changing themes in IE

---

static/web.html
static/web.js

Although not the canonical form, an empty path is a legal URL according
to RFC 3986; however, is.gd has started rejecting it some time in the
past few days, so let’s go with the canonical form which does work
rather than saving three characters (when URL encoded) out of our quota
of five thousand.

Fix link shortening.

---

README.md

r? @alexcrichton 
Following these directions I was able to get an instance of the bot onto IRC. Please double check that the things I said about channel keys and the password in `irc.yaml` are correct. 
I'll also document installing all the non-bot components, but I'm about to make some major changes to the init script to make it less Arch-dependent, so it doesn't make sense to write docs for a component I'm about to replace.

Document IRC bot use and setup

---

README.md

Reading the instructions, I thought I need to get an ApiKey, which is deprecated, and doesn't work.

README.md: Clarify you need an OAuth access token for url shortening

---

static/web.css

The flexbox spec changed, so that if we want #editor and #result to cover 60 %
and 40 % of the code box, we need to give their parent a size that can be
determined without measuring content.
Chromium has already updated their implementation, making the Playpen really
annoying to use, and Firefox will update theirs eventually.

Give <main> a definite flex basis (fixes #112)

---

README.md
bot.py

Rust playpen and bitly.com are both available over https, so link
to them that way by default.

Update links to use https.

---

static/web.js

I did a bit of research, and `[0m` seems to be the standard "reset format" ANSI token. I can't find much information on using a simple `[m` instead, but it must is supported by many terminals.
Anyway, rustc switched from `[m` to `[0m` in a recent nightly. This broke `ansi2html`'s regex, which was only expecting `[m`.
This should address and close #157.

Support standard `ansi2html` escape delimiter

---

static/web.css

In Safari (and therefor on iOS), the playpen layout in broken: There is a large gap between the code editor and the compiler output.
Safari does not support the `unset` value of CSS3. Adding a fallback to `initial` seems to work for now.
This is kind of a drive-by PR. I have only tested it locally in Safari 9 and Chrome 48 (both by editing the CSS in the dev tools) and haven't had the chance to see its effects in Firefox.

Update CSS to Fix Layout in Safari

---

bin/evaluate.sh
init.sh
static/web.css
static/web.html
static/web.js
web.py

This adds another "MIR" button next to "LLVM IR", which invokes `rustc --unpretty mir`. Since that only works in nightly, this currently ignores the channel selection.
Closes #154

Allow printing MIR

---

static/web.html

Fixes #180.
Here's a example of something that is currently highlighted incorrectly on playpen and fixed by the update:
```
fn main() {
let test = 1_2.3E+7f32;
}
```
This also adds Subresource Integrity (SRI) hashes for external javascript files, although ace will pull down additional javascript files from the CDN when setting the mode and theme that don't seem to be validated.

Update ace to 1.2.3

---

static/web.js

To test this, press Format button on this sample code to cause a rustfmt panic:
https://play.rust-lang.org/?gist=8b133106dd19821a06ee68be3a922ebe&version=stable&backtrace=1
This is a fix for PR #191

fix: backtrace wasn't properly passed to [Format]

---

static/web.css
static/web.html
static/web.js

This is a continuation of #143
Hyperlink line numbers, **Features:** 
* temporarily move into view the line(or region) that the mouse hovers on eg. line: `<anon>:3` region: `<anon>:3:5: 3:10`
* restore view when mouse doesn't hover on such lines. (wherever you left your cursor while editing)
* when left clicked, move cursor at the beginning of the specified line(or region)
In this PR I tried to address [Alex's comments](https://github.com/rust-lang/rust-playpen/pull/143/files#r35566375).
All the [hard work](https://github.com/rust-lang/rust-playpen/pull/143) is actually done by @mcast ! Much appreciated!
Screenshots (look at **mouse hover**):
And this is **mouse left click**:
**EDIT:** fixed last screenshot which wasn't showing the cursor(blinking - timing)

Hyperlink line numbers ( continuation of #143 )

---

static/web.js

(unless already focused)
After eg. Run, quickly focus back to the editor by pressing either Esc or
Enter key.
Wanted effect:
* preserves cursor position in editor
(without this  you'd have to LMB(EDIT: LMB to exactly where the cursor is already), or Shift+Tab a variable number of times)
Side effect:
* clicking outside of editor area (eg. background) will allow you to
refocus editor via Esc/Enter
* **Ctrl+Enter** (to Run) is also affected in the sense that the **editor remains focused**, which differs from before(unfocused after Run).  (if this isn't wanted, we could either remove Enter, and leave just Esc key, or find another way to "eat"/ignore Enter key from Ctrl+Enter)
Unaffected:
* Esc/Enter do not affect/interfere with options selection within Settings.
* Esc/Enter have no effect …

Focus editor via Esc or Enter key(s) especially after a Run.

---

mirlexer.py
web.py

Also fixes the problem of insufficient HTML escaping of MIR output
by neither highlighting nor escaping it.

Add a Pygments lexer for MIR output, and fix HTML escaping.

---

static/web.js

The current nightlies add the following:
* color+bold sequences
* unpaired "reset" before a color+bold sequence
Fixes: #205

Fix for new escape sequences in nightly compiler.

---

static/web.js

This irked me a little. I've added target="_new" to the formatted explain links so they open in a new window or tab rather than the page.

Open compiler explain links in a new window/tab by default

---

static/web.js

Fix for #210.
Simply adds `editor.focus()` onto the `onclick` handler for the evaluate button.
I also experimented with automatically focusing when typing (noticed some of this logic was already there), returning focus when pressing any button, etc, but this seemed like the most intuitive option and doesn't break tabbing or anything more intrusive.

Focus back on editor after clicking evaluate

---

src/bin/playbot.rs

Sets names for threads, kills the whole process when a thread panics, and logs the channel from which playbot was talked to.
Closes #225

Make debugging playbot easier

---

src/bin/playbot.rs

Right now, playbot ignores `playbot:1` while accepting `playbot:10`. In addition, it attempts to compile lines like `playbot foo` without requiring `:` or `,`, which gets awkward when trying to talk *about* playbot rather than invoke it. This PR fixes both problems.

Fix message parsing

---

src/bin/playbot.rs

Allows ops to invite playbot back into the channel if it gets kicked,
which sometimes happens due to flood limits.

Playbot: respond to invites if channel is in config

---

src/bin/playbot.rs

Example:
```
[22:52:04]  <curtism>	playbop: VERSION
[22:52:04] -playbop-	"rustc 1.10.0 (cfcb716cf 2016-07-03)"
[22:52:10]  <curtism>	playbop: --nightly VERSION
[22:52:10] -playbop-	"rustc 1.12.0-nightly (1225e122f 2016-07-30)"
```
Open to alternate syntaxes and any suggestions for improving the code... It feels a little awkward to me.

Playbot: parse --nightly, etc. playbot message prefix

---

Cargo.lock

to ensure the `url` version depended on no longer includes invalid TOML syntax in it's manifest.

run `cargo update`

---

src/docker.rs

This should fix #245 and fix rust-lang/rust-by-example#793.
I have tested the new playpen version with `docker 1.12` and verified that `--env=FOO=bar` works on `docker 1.11` (something like `./docker run --env=ABC=foo -it ubuntu`) so I'm pretty confident that this should fix the issues.

fix docker version < 1.12

---

docker/bin/compile.sh
docker/bin/evaluate.sh
src/lib.rs

This PR prints the version of the compiler before executing it.
This change may potentially be a bit controversial so you may want to consider this as some kind of RFC, however I think it's nice to get confirmation of the rust version used and the additional line of output does not really distract from the actual output (Although the situation may be a bit different for [rust-lang/rust-by-example](https://github.com/rust-lang/rust-by-example/), I'm not completely sure how they use the playpen api). 
Fixes #241.

print rustc version before compiling

---

static/web.html

This reverts commit 9cc8d06fe8e94777e51d85117ccc486504380e6b in order to undo the regression reported in https://github.com/rust-lang/rust-playpen/issues/262.
Should this close #262? If so, we should probably open another issue to track updating Ace without enabling auto-matching for single quotes.

Revert "update ace to 1.2.6"

---

static/web.html
static/web.js

This PR updates ACE to 1.2.6 once again. It works around the previously encountered issue #262 (autopairing of single quotes).
I believe that the undesired behaviour was introduced in ajaxorg/ace@b2e85158bcf3e0e72fc6856701052b9594be1a93 on the ace side. A proper fix on the ace side seems to be non-trivial, however just patching ace to never autopair single quotes look like it could be easily done.
To avoid having to fork, build and deploy ace ourselves in the case of the easy fix (or an upstreamed fix if we don't want to wait an indeterminate amount of months for the next ace release), I implemented a workaround in our JavaScript which prevents the autopair behaviour for single quotes by hijacking single quote as a hotkey (see the comments in the workaround).
If it would be acceptable / …

Hijack single quote (and update ace again)

---

src/bin/playpen.rs

The new error format broke all the `addMarker` calls for gitbook-plugin-rust-playpen. I'm trying to restore that functionality, and this seems like a good first step.

Add support for error-format=json

---

src/bin/playbot.rs

When playbot outputs an error, it is verbose and mostly unhelpful.
```
<breeden1> playbot: impl Bob for S { }
-- Notice(playbot): error[E0405]: trait `Bob` is not in scope
-- Notice(playbot):   --> <anon>:10:14
-- Notice(playbot):    |
-- Notice(playbot): (output truncated; full output at http://bit.ly/2hRZJAY)
```
Here we truncate the output to 2 lines.  Displaying both lines if there is only 2 lines, and displaying only 1 line if there is more than two.  This also handles the common scenario when executed with a simple `println!(..)`.  Example output:
```
<breeden1> playbit: impl Bob for S { }
-- Notice(playbit): error[E0405]: trait `Bob` is not in scope
-- Notice(playbit): (output truncated; full output at http://bit.ly/2j5qnlY)
```
```
<breeden1> playbit: println!("Hello!");
-- …
```

Reduce the maximum number of output lines to 2 in playbot

---

static/web.js

Fixes #271
rust-lang/rust#38660 (I assume) made a slight change to rustc's output, which was then no longer handled by the coloring regexes.

fix nightly highlighting

---

src/bin/playbot.rs

Fix #276 
Short summary: playbot will exceed `RecvQ` limits on IRC and disconnect if given an input of 4997 (but seems to be fine with 4350, so the limit is some number between these two).  Either way, that's quite excessive for an IRC bot limited to two lines of output.
This PR reduces the maximum output to 3k bytes.

playbot -- reduce maximum output size to 3000

---

static/web.js

Selects/jumps to the relevant code when you hover/click a comment in MIR output like:
```
// scope 3 at <anon>:1:10: 1:15
```

Highlight spans in MIR comments
