rust-lang/rust-playpen

bot.py

The bot is currently broken since playpen updated to beta.

Remove unstable parts of the bot's template

---

bin/format.sh
static/web.js

Remove the format button properly.

---

static/web.css
static/web.html
static/web.js

- Themes in the results pane
- Replace the 0/1/2/3 optimization selector with a debug/release mode selector.
As usual, http://temp.chrismorgan.info/rust-playpen/static/web.html is running this code at present.

Some more improvements for the web UI

---

static/web.css
static/web.html
static/web.js

Also another minor tweak while I’m at it.
As usual, http://temp.chrismorgan.info/rust-playpen/static/web.html is currently running this code.
Fixes #95.

Fix layout issues that plagued Chromium

---

static/web.html
static/web.js

This was a minor inconvenience that I had forgotten to fix up.

Focus the editor on page load.

---

static/web.js

At the end was good, but constantly is far better for Firefox.

Force repainting during the shortening animation.

---

static/web.js

A couple issues were brought up in https://github.com/rust-lang/rust-playpen/pull/108

A couple fixes from my previous pull request

---

static/web.html
static/web.js

Fixes errors from #127.
Tested the JS properly, and didn't try to do anything clever with git this time. Sorry for the noise!

Fix styles and broken selector

---

static/web.js

This just makes selecting an asm flavor persistent

Persist asm flavor

---

bin/evaluate.sh
static/web.html
static/web.js

With this little gimmick you can have the word “ok” appear in green and
the word “FAILED” in red. Isn’t life great?

Force colours in the test runner.

---

README.md
bot.py

Reverts rust-lang/rust-playpen#142

Revert "Change the IRC interface for easier usage and channel selection"

---

README.md

Document updater services

---

bin/format.sh
init.sh
static/web.html
static/web.js
web.py

Add support for rustfmt

---

static/web.html

Bump the web.js "cache buster"

---

static/web.js

See #200.
This time, I set up an Arch VM and tested with the full instance.

Fix MIR output: add mappings for Pygments styles

---

bin/compile.sh
bin/evaluate.sh
static/web.js

Switch to RUST_NEW_ERROR_FORMAT on nightly and adapt the parsing regexes for error numbers and locations.

Use new rustc error format.

---

static/web.html

... without removing it. That would cause an error in the JS file.

Visually hide the format button (fix #217)

---

src/bin/playbot.rs

Fix playbot-mini

---

src/bin/playbot.rs

Enable `should_ghost` for playbot

---

src/bin/playbot.rs
src/bin/playpen.rs
src/docker.rs
src/lib.rs

Fixes #229
(I'm not really sure about the usefulness of the `auto` setting, but kept it for compatibility with the previous implementation.)

re-add backtrace functionality

---

docker/bin/compile.sh
docker/bin/evaluate.sh
src/bin/playbot.rs
src/bin/playpen.rs
src/lib.rs

don't print version for playpot

---

static/web.js

Fix typo in formatMirScopes function
